<a href="https://colab.research.google.com/github/Perovsky56/ARCH_Project/blob/main/Tensors_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
tensor1 = torch.arange(20)
tensor1

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [5]:
# Reshape and View for tensors
tensor1 = tensor1.reshape(4, 5)
tensor1

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [6]:
# Reshape without knowledge about number of elements in tensor
tensor2 = torch.arange(20)
tensor2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [7]:
tensor2 = tensor2.reshape(2,-1)
tensor2

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [8]:
torch3 = torch.arange(20)
torch3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [10]:
torch4 = torch3.view(2,10)
torch4

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [11]:
torch5 = torch.arange(10)
torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
torch6 = torch5.reshape(2,5)
torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
torch5[1] = 1982
torch5

tensor([   0, 1982,    2,    3,    4,    5,    6,    7,    8,    9])

In [14]:
torch6

tensor([[   0, 1982,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [15]:
# Slices
torch7 = torch.arange(10)
torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
torch7[7]

tensor(7)

In [18]:
# Grab a slice
torch8 = torch7.reshape(5,2)
torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [19]:
torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [20]:
# Return column
torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])